name: CI/CD

on:
  push:
    branches: [ creation ]
  pull_request:
    branches: [ creation ]

jobs:

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: list importmap content
        run: cat deno.importmap
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: fullfrontal # the name of the project on Deno Deploy
          import-map: deno.importmap
          entrypoint: server.tsx # the entrypoint to deploy
